server:
  port: 8081

spring:
  application:
    name: The First Spring Boot 3 App
  jpa:
    open-in-view: false
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
